### ISSUE TITLE
Combined current_day_rates and next_day_rates

### ISSUE THREAD

**Issue by FireFury0** [BottlecapDave/HomeAssistant-CarbonIntensity#19]
### Describe the feature

We currently have today's forecast as attributes in the current_day_rates entity, and tomorrow's forecast as attributes in the next_day_rates entity.  Having 2 separate entities makes it somewhat complex to use these data - i.e. if I want to graph all of the forecast data, my graphs need to have a separate data series for each day rather than just specifying a single series.  (And as far as I can tell, HA doesn't have a simple way of combining these data into a single entity).

It would be very useful to provide an entity which contains all of the forecast data within a single entity.

### Expected behaviour

There should be an entity which has attributes containing all of the forecast data.

### Use Case

Graphing forecast carbon intensity and generation.

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-FirstBus) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. The previous, current and next data was once in a single entity. However lots of warnings were raised by HA as the data was too large, which is why it's been split across entities. Because of this, there are no plans to contain this data in a single entity.

You can always use a template sensor to join the entity data together. Or you might be interested in a community written card for displaying the rates https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/community/#agile-price-table
